kind: pipeline
name: github

steps:
- name: bstn
  image: yellowmegaman/pckrdckr:1.3.3
  environment:
    APP: bstn
    DOCKER_HOST: tcp://serviced:2375
    FROM_IMAGE: "alpine:3.8"
    GLIDER_VERSION: 0.6.9
    PROJECT_NAME: yellowmegaman
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
    QUAY_USERNAME:
      from_secret: quay_username
    QUAY_PASSWORD:
      from_secret: quay_password
  commands:
  - packer build "$APP".json

services:
- name: serviced
  image: plugins/docker
  entrypoint: [ dockerd ]
  command: [ '-H', 'tcp://0.0.0.0:2375', '--iptables=false' ]
